# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-24 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lee', '0002_remove_userinfo_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='site',
            field=models.CharField(max_length=32, null=True, unique=True, verbose_name='个人博客前缀'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='theme',
            field=models.CharField(max_length=32, null=True, verbose_name='博客主题'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=64, null=True, verbose_name='个人博客标题'),
        ),
    ]
