# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-30 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lee', '0003_auto_20180124_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.AddField(
            model_name='article',
            name='category_id',
            field=models.IntegerField(choices=[(1, '原创'), (2, '转载'), (3, '翻译'), (4, '其他')], default=None),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_type_id',
            field=models.IntegerField(choices=[(1, 'Web开发'), (2, '数据库'), (3, '网络技术'), (4, '爱生活爱自己'), (5, 'Linux世界'), (6, '开发语言')], default=None),
        ),
    ]
