# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-30 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lee', '0004_auto_20180130_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category_id',
            field=models.IntegerField(choices=[(1, '原创'), (2, '转载'), (3, '翻译'), (4, '其他')], default=None, null=True),
        ),
    ]
