# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-30 02:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lee', '0006_auto_20180130_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='category_id',
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lee.Category', verbose_name='文章类型'),
        ),
    ]
